/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.pauldaniv.file.metadata;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        Main classUnderTest = new Main();
        // no tests for now
    }
}
